name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: pipeline-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    uses: danielvm-git/.github/.github/workflows/test-build-release-php.yml@main
    with:
      site_url: "https://php.bigbase.click"
      release_tool: "big-release"
    secrets: inherit
